version = "0.3.X"
summaryLength = 25

[page]
[page.math]
enable = true
blockLeftDelimiter = "\\["
blockRightDelimiter = "\\]"
inlineLeftDelimiter = "\\("
inlineRightDelimiter = "\\)"
copyTex = true
mhchem = true
